// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	types "bruteforce/internal/types"

	mock "github.com/stretchr/testify/mock"
)

// GroupItem is an autogenerated mock type for the GroupItem type
type GroupItem struct {
	mock.Mock
}

// GetAllGroupData provides a mock function with given fields:
func (_m *GroupItem) GetAllGroupData() *types.AllGroupData {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllGroupData")
	}

	var r0 *types.AllGroupData
	if rf, ok := ret.Get(0).(func() *types.AllGroupData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AllGroupData)
		}
	}

	return r0
}

// GetCapacity provides a mock function with given fields:
func (_m *GroupItem) GetCapacity() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapacity")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetLeakageRate provides a mock function with given fields:
func (_m *GroupItem) GetLeakageRate() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLeakageRate")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// GetLenQueue provides a mock function with given fields:
func (_m *GroupItem) GetLenQueue() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLenQueue")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// IsAllowed provides a mock function with given fields: id, drops
func (_m *GroupItem) IsAllowed(id string, drops int64) bool {
	ret := _m.Called(id, drops)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, int64) bool); ok {
		r0 = rf(id, drops)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RemoveDrops provides a mock function with given fields: id
func (_m *GroupItem) RemoveDrops(id string) {
	_m.Called(id)
}

// NewGroupItem creates a new instance of GroupItem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupItem(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupItem {
	mock := &GroupItem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
