// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	types "bruteforce/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// SpecListsManager is an autogenerated mock type for the SpecListsManager type
type SpecListsManager struct {
	mock.Mock
}

// AddID provides a mock function with given fields: id, isBlack
func (_m *SpecListsManager) AddID(id string, isBlack types.IsBlack) bool {
	ret := _m.Called(id, isBlack)

	if len(ret) == 0 {
		panic("no return value specified for AddID")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, types.IsBlack) bool); ok {
		r0 = rf(id, isBlack)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DelID provides a mock function with given fields: id
func (_m *SpecListsManager) DelID(id string) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DelID")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetIDsMap provides a mock function with no fields
func (_m *SpecListsManager) GetIDsMap() map[string]types.IsBlack {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIDsMap")
	}

	var r0 map[string]types.IsBlack
	if rf, ok := ret.Get(0).(func() map[string]types.IsBlack); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.IsBlack)
		}
	}

	return r0
}

// GetName provides a mock function with no fields
func (_m *SpecListsManager) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Reset provides a mock function with no fields
func (_m *SpecListsManager) Reset() {
	_m.Called()
}

// ToFind provides a mock function with given fields: id
func (_m *SpecListsManager) ToFind(id string) (bool, types.IsBlack, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ToFind")
	}

	var r0 bool
	var r1 types.IsBlack
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, types.IsBlack, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) types.IsBlack); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(types.IsBlack)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewSpecListsManager creates a new instance of SpecListsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecListsManager(t interface {
	mock.TestingT
	Cleanup(func())
},
) *SpecListsManager {
	mock := &SpecListsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
