logger:
  level: Info

database:
  is_postgres: true
  database: calendar

is_postgres:
  host: localhost
  port: 7777
  user: user
  password: pass

reindexer:
  namespace: events
  host: localhost
  port: 7778

http_server:
  host: localhost
  port: 7779

grpc_server:
  host: localhost
  port: 7780

swagger_server:
  host: localhost
  port: 7781

rabbitmq:
  # url: "amqp://guest:guest@localhost:5672/"
  host: localhost
  port: 5672
  user: guest
  password: guest
  queue: "notifications"
