// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	config "bruteforce/config"
	types "bruteforce/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// AbstractManager is an autogenerated mock type for the AbstractManager type
type AbstractManager struct {
	mock.Mock
}

// AddToSpecList provides a mock function with given fields: name, id, isBlack
func (_m *AbstractManager) AddToSpecList(name string, id string, isBlack types.IsBlack) bool {
	ret := _m.Called(name, id, isBlack)

	if len(ret) == 0 {
		panic("no return value specified for AddToSpecList")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, types.IsBlack) bool); ok {
		r0 = rf(name, id, isBlack)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DelFromSpecList provides a mock function with given fields: name, id
func (_m *AbstractManager) DelFromSpecList(name string, id string) bool {
	ret := _m.Called(name, id)

	if len(ret) == 0 {
		panic("no return value specified for DelFromSpecList")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(name, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetParams provides a mock function with given fields: name
func (_m *AbstractManager) GetParams(name string) config.GroupParams {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetParams")
	}

	var r0 config.GroupParams
	if rf, ok := ret.Get(0).(func(string) config.GroupParams); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(config.GroupParams)
	}

	return r0
}

// IsAllowed provides a mock function with given fields: nameGroup, idBucket, drops
func (_m *AbstractManager) IsAllowed(nameGroup string, idBucket string, drops int64) bool {
	ret := _m.Called(nameGroup, idBucket, drops)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, int64) bool); ok {
		r0 = rf(nameGroup, idBucket, drops)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsRequestAllowed provides a mock function with given fields: params
func (_m *AbstractManager) IsRequestAllowed(params types.RequestParams) bool {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for IsRequestAllowed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(types.RequestParams) bool); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewGroup provides a mock function with given fields: name, params
func (_m *AbstractManager) NewGroup(name string, params config.GroupParams) error {
	ret := _m.Called(name, params)

	if len(ret) == 0 {
		panic("no return value specified for NewGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, config.GroupParams) error); ok {
		r0 = rf(name, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetBacket provides a mock function with given fields: name, id
func (_m *AbstractManager) ResetBacket(name string, id string) error {
	ret := _m.Called(name, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetBacket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAbstractManager creates a new instance of AbstractManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAbstractManager(t interface {
	mock.TestingT
	Cleanup(func())
},
) *AbstractManager {
	mock := &AbstractManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
