params:
  ip:
    lenQueue: 10
    capacity: 4
    leakageRate: 0.25
    # leakageRate: 16.666666666666668   # 100/6    
  login:
    lenQueue: 10
    capacity: 4
    leakageRate: 0.5
    # leakageRate: 0.16666666666666666  # 1/6
  pass:
    lenQueue: 10
    capacity: 4
    leakageRate: 1
    # leakageRate: 1.6666666666666667   # 10/6    
default:
  lenQueue: 100
  capacity: 10
  leakageRate: 0.5

logger:
  level: info

http_server:
  scheme: http
  host: 127.0.0.1
  port: 3009

is_test: true