version: '3.8'

services:
  bruteforce_service:
    build:
      context: ./bruteforce
      dockerfile: Dockerfile
    container_name: bruteforce_service_container
    # Нужен 'network_mode: "host"', а для этого порты не пробрасываем
    # ports:
    #   - "3009:3009"
    environment:
      - DOCKER_CONF_PATH=/bin/
    network_mode: "host"
    command: /bin/bruteforce_service